baseURL = 'https://grafmaxi.github.io/maximilian-graf/'
languageCode = 'en-us'
title = 'Maximilian Graf'
theme = "PaperMod"

[params]
  defaultTheme = "auto"

  [params.profileMode]
    enabled = true
    subtitle = "Universität Potsdam"
    imageUrl = "{{ \"images/profile.png\" | relURL }}"
    imageTitle = "Portrait of Max"
    imageWidth = 160
    imageHeight = 160


[[params.profileMode.buttons]]
name = "About Me"
url = "about/"